name: VITE_REACT_BIGDATA_DEPLOY
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 打包

      - name: move
        run: cp README.md dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.VITE_REACT_BIGDATA_DEPLOY }} # secret 名
          publish_branch: gh-pages
          commit_message: 'feat: view react bigdata' # 部署时的 git 提交信息，自由填写
